### ISSUE TITLE
Graph neural network in PyTorch

### ISSUE THREAD

**Issue by Anindyadeep** [python-engineer/blogposts-pythonengineer#2]
I have been studying GNNs and GraphML for some time now, as well as done research on VGAEs. So I want to contribute here. I will make blogs on the math of inner working of GNN algorithms, and code in pytorch geometric.

**Comment by python-engineer** [comment]
This sounds exciting! I would love to add articles about these topics on my blog

**Comment by Anindyadeep** [comment]
Ok, so I have to write my article in the markdown format right? And after that have to make my branch and submit my files in the blog/content (of my branch) and make a pull request?

**Comment by python-engineer** [comment]
exactly. I also added a section in the README about the author information you can submit

**Comment by Anindyadeep** [comment]
Great... so i am starting to write...
